"""initial schema

Revision ID: b3edfc8848eb
Revises:
Create Date: 2026-04-29 18:03:31.216575+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b3edfc8848eb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secrets",
        sa.Column(
            "scope",
            sa.Enum("cluster", "application", "registry", "global_", name="secret_scope"),
            nullable=False,
        ),
        sa.Column("scope_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_secrets")),
        sa.UniqueConstraint("scope", "scope_id", "name", name="uq_secrets_scope_id_name"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("admin", "member", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_table(
        "clusters",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("in_cluster", sa.Boolean(), nullable=False),
        sa.Column("kubeconfig_secret_id", sa.Uuid(), nullable=True),
        sa.Column("default_namespace", sa.String(length=63), nullable=False),
        sa.Column(
            "status",
            sa.Enum("unknown", "healthy", "unreachable", name="cluster_status"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kubeconfig_secret_id"],
            ["secrets.id"],
            name=op.f("fk_clusters_kubeconfig_secret_id_secrets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clusters")),
        sa.UniqueConstraint("name", name=op.f("uq_clusters_name")),
    )
    op.create_table(
        "applications",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("repo_url", sa.String(length=512), nullable=False),
        sa.Column("repo_owner", sa.String(length=128), nullable=False),
        sa.Column("repo_name", sa.String(length=128), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("namespace", sa.String(length=63), nullable=False),
        sa.Column("image_repository", sa.String(length=512), nullable=False),
        sa.Column("webhook_secret_id", sa.Uuid(), nullable=True),
        sa.Column("build_config_yaml", sa.Text(), nullable=True),
        sa.Column("auto_deploy", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name=op.f("fk_applications_cluster_id_clusters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["webhook_secret_id"],
            ["secrets.id"],
            name=op.f("fk_applications_webhook_secret_id_secrets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint(
            "repo_owner",
            "repo_name",
            "default_branch",
            name="uq_applications_repo_owner_name_branch",
        ),
        sa.UniqueConstraint("slug", name=op.f("uq_applications_slug")),
    )
    op.create_table(
        "build_runs",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("commit_message", sa.Text(), nullable=True),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column(
            "source",
            sa.Enum("webhook", "manual", "api", "retry", name="build_source"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "building",
                "pushing",
                "succeeded",
                "failed",
                "cancelled",
                name="build_status",
            ),
            nullable=False,
        ),
        sa.Column("image_tag", sa.String(length=255), nullable=True),
        sa.Column("image_digest", sa.String(length=128), nullable=True),
        sa.Column("log_object_key", sa.String(length=512), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_build_runs_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_build_runs")),
    )
    op.create_index(
        "ix_build_runs_application_id_created_at",
        "build_runs",
        ["application_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "deployments",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("build_run_id", sa.Uuid(), nullable=True),
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("namespace", sa.String(length=63), nullable=False),
        sa.Column("image_tag", sa.String(length=255), nullable=False),
        sa.Column("image_digest", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "applying",
                "rolling_out",
                "succeeded",
                "failed",
                "rolled_back",
                name="deployment_status",
            ),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_deployments_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["build_run_id"],
            ["build_runs.id"],
            name=op.f("fk_deployments_build_run_id_build_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name=op.f("fk_deployments_cluster_id_clusters"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployments")),
    )
    op.create_index(
        "ix_deployments_application_id_created_at",
        "deployments",
        ["application_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_deployments_application_id_created_at", table_name="deployments")
    op.drop_table("deployments")
    op.drop_index("ix_build_runs_application_id_created_at", table_name="build_runs")
    op.drop_table("build_runs")
    op.drop_table("applications")
    op.drop_table("clusters")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("secrets")
    # ### end Alembic commands ###

    # Postgres enum types are not dropped automatically when their referencing
    # tables are dropped. Explicit cleanup keeps `downgrade base` followed by
    # `upgrade head` idempotent.
    for type_name in (
        "deployment_status",
        "build_status",
        "build_source",
        "cluster_status",
        "user_role",
        "secret_scope",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {type_name}"))
