"""application_deploy_overrides

Revision ID: 3adac58ac0c7
Revises: b3edfc8848eb
Create Date: 2026-05-01 21:02:03.301561+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3adac58ac0c7"
down_revision: str | None = "b3edfc8848eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOT NULL on existing rows requires a server-side default during the
    # backfill. Drop the default afterwards so the ORM-side default takes
    # over for new rows.
    op.add_column(
        "applications",
        sa.Column("app_port", sa.Integer(), nullable=False, server_default="8080"),
    )
    op.alter_column("applications", "app_port", server_default=None)
    op.add_column(
        "applications",
        sa.Column(
            "health_check_path",
            sa.String(length=255),
            nullable=False,
            server_default="/healthz",
        ),
    )
    op.alter_column("applications", "health_check_path", server_default=None)
    op.add_column(
        "applications",
        sa.Column("replicas", sa.Integer(), nullable=False, server_default="1"),
    )
    op.alter_column("applications", "replicas", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "replicas")
    op.drop_column("applications", "health_check_path")
    op.drop_column("applications", "app_port")
    # ### end Alembic commands ###
