"""build_run_inferred_defaults_json

Revision ID: ca2d0955d0fc
Revises: 7b5e46aa8dec
Create Date: 2026-05-02 17:24:27.581310+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ca2d0955d0fc"
down_revision: str | None = "7b5e46aa8dec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "build_runs",
        sa.Column("inferred_defaults_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("build_runs", "inferred_defaults_json")
    # ### end Alembic commands ###
