{{- if .Values.serviceAccount.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liftwork.api.serviceAccountName" . }}
  namespace: {{ include "liftwork.namespace" . }}
  labels:
    {{- include "liftwork.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccount.worker.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liftwork.worker.serviceAccountName" . }}
  namespace: {{ include "liftwork.namespace" . }}
  labels:
    {{- include "liftwork.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.worker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccount.dashboard.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liftwork.dashboard.serviceAccountName" . }}
  namespace: {{ include "liftwork.namespace" . }}
  labels:
    {{- include "liftwork.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.dashboard.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
